# Generated by Django 5.1.3 on 2025-03-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
